steps:
- name: node:20.12.1
  entrypoint: npm
  args: ['install']
- name: node:20.12.1
  entrypoint: npx
  args: ['selfage', 'run', 'updater_test']
  env:
  - 'PROJECT_ID=${PROJECT_ID}'
  - 'INSTANCE_ID=${_INSTANCE_ID}'
  - 'DATABASE_ID=${_DATABASE_ID}'
- name: node:20.12.1
  entrypoint: npx
  args: ['bundage', 'bfn', 'main', 'main_bin', '-t', 'bin']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/spanner_schema_update_cli', '.']
images: ['gcr.io/${PROJECT_ID}/spanner_schema_update_cli']
options:
  logging: CLOUD_LOGGING_ONLY
